services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /app/uploads
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_HOST=cache

  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
